---
- name: Run Evidence of Compromise scan via Symantec Endpoint Protection Manager
  hosts: epm
  gather_facts: no
  connection: httpapi
  vars:
    ansible_network_os: symantec.epm.epm
    ansible_user: Admin
    ansible_httpapi_port: 8446
    ansible_httpapi_validate_certs: no
    ansible_httpapi_use_ssl: yes
  tasks:
    - name: Query for a list of computers in the inventory to run scan against
      symantec.epm.computers_info:
      register: computers_info

    - name: Query for a list of groups in the inventory to run scan against
      symantec.epm.groups_info:
      register: groups_info

    - name: Schedule Evidence of Compromise scan on endpoints
      symantec.epm.full_scan:
        computers: "{{computers_info['id_list']}}"
        groups: "{{groups_info['id_list']}}"

